config/routes.rb
Rails.application.routes.draw do

  # Route for commontator
  mount Commontator::Engine => '/commontator'

  devise_for :admins
  root to: 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get '/quan-ly-nguoi-dung', to: 'user#index', as: 'user'
  get '/quan-ly-nhom-nguoi-dung', to: 'group#index', as: 'group'
  post '/add-user', to: 'user#add_list'
  get '/nguoi-dung/:id/sua', to: 'user#edit', as: 'user_edit'
  patch '/nguoi-dung/:id/sua', to: 'user#update', as: 'user_update'

  get '/groups/new', to: 'group#new'
  post '/groups/new', to: 'group#create'

  get '/quan-ly-khoa-hoc', to: 'course#index', as: 'course'
  post '/courses/new', to: 'course#create', as: 'course_new'
  get '/khoa-hoc/:id/chi-tiet', to: 'course#detail', as: 'course_detail'

  get '/quan-ly-chu-de', to: 'topic#index', as: 'topic'
  post '/topics/new', to: 'topic#create', as: 'topic_new'

  get '/them-noi-dung/:course_id/:type_id', to: 'lesson#new', as: 'lesson_new'
  post '/them-noi-dung/:course_id/:type_id', to: 'lesson#create', as: 'lesson_create'
  get '/noi-dung/:id/sua', to: 'lesson#edit', as: 'lesson_edit'
  patch '/noi-dung/:id/sua', to: 'lesson#update', as: 'lesson_update'

  get '/noi-dung-bai-hoc/:id', to: 'lesson#show', as: 'lesson_detail'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :course_teachers, class_name: 'CourseTeacher'
  has_many :teachers, through: :course_teachers, source: :teacher
  belongs_to :head_teacher, class_name: 'Teacher'
  has_many :lessons
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
  before_action :authenticate_user!

  def index
    @courses = Course.all
    @users = User.all
    @course = Course.new
  end

  def new

  end

  def create
    course = Course.new(course_params)
    if course.save

    else
      @error = true
    end
    @courses = Course.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update

  end

  def detail
    @course = Course.find_by_id(params[:id])
    @lessons = @course.lessons
  end

  private
  def course_params
    params.require(:course).permit(:name, :topic, :introduction, :head_teacher_id, teacher_ids: [])
  end
end

app/views/course/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th>Khóa học</th>
    <th>Chức năng</th>
  </tr>
  </thead>
  <tbody>
  <% if @courses.length > 0 %>
      <% @courses.each do |course| %>
          <tr>
            <td><%= link_to course.name, course_detail_path(id: course.id) %></td>
            <td>
              <span class="fa fa-pencil"></span>
              <span class=" fa fa-trash-o" title="Xoá"></span>
            </td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/course/_new.html.erb
<button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
</button>
<h4 style="font-size:14px;text-align:center">THÊM KHÓA HỌC</h4>
<div class="separator"></div>
<div id="SuaKhoaHoc"></div>
<div class="modal-body">
  <%= form_for @course, url: course_new_path, method: 'POST', remote: true do |f| %>
      <!--Toàn bộ thông tin khóa học-->
      <div class="display-information">
        <!--Tên khóa học-->
        <div class="lms-input-group">
          <div class="input-group-title right">Tên khóa học (*)</div>
          <div class="input-group-content">
            <!--<input id="TenKhoaHoc" class="form-control" maxlength="255" name="TenKhoaHoc" style="border: 1px solid rgb(204, 204, 204);" type="text">-->
            <%= f.text_field :name, class: "form-control", maxlength: 255, style: "border: 1px solid rgb(204, 204, 204);" %>
          </div>
          <div id="errorNameCourse" class="error-message pull-right" style="display:none"></div>
        </div>
        <!--Danh sách chủ đề-->
        <div class="lms-input-group">
          <div class="input-group-title right">Chủ đề</div>
          <div class="input-group-content">
            <!--<select id="SelectCategories" class="form-control">-->
            <!--<option data-value="0">Lựa chọn chủ đề</option>-->
            <!--</select>-->
            <%= f.collection_select :topic, Topic.all, :id, :name, {}, class: "form-control" %>
          </div>
        </div>
        <!--Ảnh đại diện-->
        <div class="col-md-6" style="margin-bottom:15px">
          <div class="select-file UploadLibrary">
            <div class="select-file-title text-center">Ảnh đại diện</div>
            <div class="select-file-thumbs" id="khuploadphoto" style="margin:0 auto" data-toggle="tooltip" data-placement="bottom" data-html="true" title="" data-original-title="Định dạng: JPG, PNG, BMP, GIF. Dung lượng tối đa: 3MB">
              <span id="btn-remove-image" onclick="XoaHinh(this)" style="z-index: 1000; display: none;">×</span>
              <img src="" id="Picture" style="width:100%;height:100%;display:none">
              <img src="/Content/Based/images/logo-khoahoc.jpg" id="PictureIcon" style="width: 100%; height: 100%;">
              <button type="button" class="btn-select-file" onclick="$('#KHUploadPhoto').trigger('click')"></button>
            </div>
            <input id="KHUploadPhoto" accept="image/*" style="font-size: 0px;width:100%;height:100%;display:none" type="file">

            <div class="text-center">
              <span class="error-message register_error_log" style="display: none;"></span>
            </div>
            <div class="upload-holder">
              <input class="filesrc" value="/Content/QuanLyKhoaHoc/images/anh-dai-dien/noavatar.jpg" type="hidden">

              <input class="fileid" value="" type="hidden">
            </div>
          </div>
        </div>
        <!--Video đại diện-->
        <div class="col-md-6" style="margin-bottom:15px">
          <div class="select-file UploadLibrary">
            <div class="select-file-title text-center">Video giới thiệu</div>
            <div class="divvideo">
              <div class="select-file-thumbs" id="khuploadvideo" data-toggle="tooltip" data-placement="bottom" data-html="true" title="" style=" margin: 0 auto;width:100%" data-original-title="Định dạng: avi, flv, mp4, wmv. Dung lượng tối đa: 300MB">
                <span class="Video-remove-icon" onclick="XoaVideo(this)" style="z-index: 1000; display: none;">×</span>

                <div id="PictureThubnail" style="width:100%;height:100%;display:none;border: 1px solid #eee;" data-video="" src=""></div>
                <div style="font-size: 80px; line-height: 140px; color: rgb(207, 204, 204);" class="VideoIcon fa fa-film"></div>
                <button type="button" class="btn-select-file" id="btn-upload-video" onclick="$('#KHVideoUpload').trigger('click')"></button>
              </div>
              <div class="KHprogess" style="height:7px;background:green;width:0%"><span id="percentProgess"></span>
              </div>
            </div>
            <input id="KHVideoUpload" style="font-size: 0px;width:100%;height:100%;display:none" accept="video/*" type="file">

            <div class="text-center">
              <span class="error-message register_error_logVideo" style="display: none;"></span>
            </div>

          </div>
        </div>
        <!--Giới thiệu khóa học-->
        <div class="lms-input-group">
          <div class="input-group-title right">Giới thiệu khóa học</div>
          <div class="input-group-content">
            <!--<textarea class="form-control GioiThieuKhoaHoc" cols="20" id="GioiThieuKhoaHoc" maxlength="4000" name="GioiThieuKhoaHoc" rows="2" style="visibility: hidden; display: none;"></textarea>-->
            <%= f.text_area :introduction, class: 'form-control', cols: 20, maxlength: 4000, rows: 2 %>

          </div>
          <div id="errorNameCourse" class="error-message pull-right" style="display:none"></div>
        </div>
      </div>

      <!--Danh sách giáo viên và những người được chỉ định làm giáo viên-->
      <div class="display-information">
        <div class="col-md-12" style="padding-left:0px">
          <h5 class="text-italic">DANH SÁCH GIÁO VIÊN</h5>
        </div>
        <!--Danh sách giáo viên-->
        <div class="lms-input-group">
          <div class="paginationContainer">
            <table class="tablecourse" id="vunggiaovien">
              <thead>
              <tr>
                <th>Tên giáo viên</th>
                <th class="text-center">Chủ khóa học</th>
                <th class="text-center">Chi tiết</th>
              </tr>
              </thead>
              <tbody>
              <!--<td>- Admin</td>-->
              <!--<td class="text-center"><input name="chukhoahoc" checked="" type="radio"></td>-->
              <tr data-manguoidung="5320" data-chu="true" class="paginationItemPage1" style="display: table-row;">
                <%= f.hidden_field :head_teacher_id, value: current_user.id %>
                <td><%= current_user.username %></td>
                <td class="text-center"><input name="chukhoahoc" checked="" type="radio"></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
        <!--Danh sách những người được chỉ định làm giáo viên-->
        <div style="padding-top : 10px;">
          <div style="display : table; margin : 20px 0px; width : 100%; height : 100%;">
            <div>
              <div style="float : left; width : 50%;">
                <input id="btnclicknguoidung" class="form-control" style="float : left; width: 15px; height: 15px; margin-right: 15px;" type="checkbox">
                <span>Thêm giáo viên</span>
              </div>
              <div style="float : right; width : 50%;">
                <div class="form-group has-feedback pull-right" style="margin: 0;">
                  <input class="form-control" placeholder="Tìm kiếm người dùng" id="txtUserSearchBox" onkeyup="searchingUser($(this).val())" type="text">
                  <span class="form-control-feedback fa fa-search"></span>
                </div>
              </div>
            </div>
            <div id="vunghienthinguoidung" style="display: none;">
              <div class="paginationContainer">
                <table id="vungnguoidung" class="tablecourse">
                  <thead>
                  <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                  </tr>
                  </thead>
                  <tbody>
				  <%= f.collection_check_boxes :teacher_ids, User.all, :id, :username do |b| %>
                  <tr data-manguoidung="4372" data-chu="true" class="paginationItemPage1" style="display: table-row;">
                    <td><%= b.text %></td>
                    <td class="text-center"><%= b.check_box %></td>
                  </tr>
				  <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!--Nút lưu và hủy-->
      <div class="button-action-group">
		<%= f.submit "Lưu", class: 'btn btn-save btn-fixed-width' %>
        <input class="btn btn-cancel btn-fixed-width" style="margin-left:10px" data-dismiss="modal" value="Hủy" type="reset">
      </div>
  <% end %>
</div>

<script>
    CKEDITOR.replace('course[introduction]', {
        language: 'vi'
    });
    $('#btnclicknguoidung').on('change', function () {
        if ($(this).prop('checked') == true) {
            $('#vunghienthinguoidung').show();
        }
        else {
            $('#vunghienthinguoidung').hide();
        }
    });
</script>

<script>
    function searchingUser(keyword) {
        $('#vungnguoidung').tvSearching({allField: true, keyword: keyword});
        returnCurrentPage();
    }

    $(document).ready(function () {
        searching($('#txtSearchBox').val());
        searchingUser($('#txtUserSearchBox').val());
    });

</script>

app/views/course/create.js.erb
$("#course-list").html("<%= j render partial: 'list' %>");
$('#add-course-modal').modal('hide');

app/views/course/detail.html.erb
<div id="moduleWrapper">
  <div id="navigator">
    <a class="home" href="/?role=instructor">
      <span class="mobile-show fa fa-book"></span>
      <span class="mobile-hide">Người dạy</span>
    </a>

    <span class="vertical-separator">/</span>
    <%= link_to "Khóa học", course_path %>
    <span class="vertical-separator">/</span>
    <a class="no-event active" href="/contents/index/5865">Quản lý nội dung</a>
  </div>
  <div id="moduleContent">
    <link href="/Content/Contents/css/Contents.css" rel="stylesheet">
    <script src="/Content/Contents/js/Contents.js"></script>
    <script src="/Content/Contents/js/bootstrap-datetimepicker/js/moment.min.js"></script>
    <link href="/Content/Contents/js/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <script src="/Content/Contents/js/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
    <style>
      .elearning-gray {
        background: #e5e5e5;
        color: black;
        outline: none;
      }

      .elearning-gray:hover {
        background: #c6c6c6;
      }

      .elearning-gray:active {
        background: #f4a211;
        color: white;
      }

      .list-item-course-handler {
        float: right;
        display: none;
      }

      .list-item-course-handler > .glyphicon {
        cursor: pointer;
      }

      .list-course-item:hover > .list-item-course-handler {
        display: block !important;
      }

      .mini-field {
        width: 60px;
        height: 35px;
      }

      .margin-left {
        margin-left: 5px !important;
      }

      .margin-right {
        margin-right: 5px !important;
      }

      .blue-sky {
        border-color: #0087eb;
        color: #0087eb;
        background-color: white;
      }

      .green-leave {
        border-color: #3e9722;
        color: #3e9722;
        background-color: white;
      }

      .dark-world {
        border-color: #555555;
        color: #555555;
        background-color: white;
      }
    </style>
    <div class="content-info-course row">
      <div class="course-title"><%= @course.name %></div>
      <div class="content-img-course">
        <%= course_avatar(@course) %>
      </div>
      <div class="content-desciption-course">
        <div style="padding:0 15px;">
          <%= @course.introduction.html_safe if @course.introduction %>
        </div>
      </div>
    </div>
    <ul class="nav nav-tabs lms-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#setting-content" aria-controls="home" role="tab" data-toggle="tab">Nội dung</a></li>

    </ul>
    <div class="tab-content lms-tab-content">
      <div id="setting-content" class="tab-pane active manage-content">
        <div class="btn-group kbtn-hidden">
          <button type="button" class="btn btn-add btn-sm dropdown-toggle limit-btn" style="width:100%" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="fa fa-plus"></span>
            Thêm nội dung
            <span class="fa fa-caret-down"></span>
          </button>
          <ul class="dropdown-menu">
            <% LessonType.all.each do |type| %>
                <li>
                  <%= link_to type.name, lesson_new_path(type_id: type.id, course_id: @course.id) %>
                </li>
            <% end %>
          </ul>
        </div>
        <button type="button" class="btn btn-add btn-sm kbtn-hidden" onclick="StartOrder()">
          <i class="fa fa-arrows-v"></i>
          Sắp xếp
        </button>
        <button type="button" class="btn btn-add btn-sm kbtn limit-btn" onclick="redirectTo('/courses/edit/5865#start=user')">
          <i class="fa fa-pencil"></i>
          Gán người dùng
        </button>
        <button type="button" class="btn btn-add btn-sm kbtn limit-btn" onclick="redirectTo('/courses/edit/5865')">
          <i class="fa fa-pencil"></i>
          Sửa thông tin
        </button>
        <button type="button" class="btn btn-add btn-sm kbtn limit-btn" style="height:auto; line-height:inherit" onclick="redirectTo('/course/info/5865')">
          <i class="fa fa-graduation-cap"></i>
          Hiển thị như người học
        </button>
        <button type="button" class="btn btn-sm blue-sky" style="float:right" onclick="UpdateCourse('request_publish_course')">
          Yêu cầu phát hành
        </button>

        <div id="DivContentController" class="content-show-content">

          <script src="/Content/Contents/jqueryui/jquery-ui.js"></script>
          <link href="/Content/Contents/jqueryui/jquery-ui.css" rel="stylesheet">
          <style>
            .content-name:hover {
              background-color: #CDE8FB;
              cursor: pointer;
            }

            .gly {
              font-size: 10px;
              top: 0;
            }

            .glyphicon-handle {
              float: right;
              cursor: pointer;
              display: block;
            }

            .list-group-item:hover > .col-sm-1 .glyphicon-handle {
              display: block;
            }

            .list-group-item:hover > .title .glyphicon-handle {
              display: block;
            }

            .list-group-item {
              cursor: pointer;
              height: 40px;
              padding-right: 0;
              /*background-color: #EBEBEB;*/
            }

            .children {
              background-color: #fff;
              height: 40px;
              padding-right: 0;
            }

            .BlankingHover {
              background-color: wheat;
            }

            .BlankingActive {
              background-color: #f0ad4e;
            }

            .ContentActive {
              background-color: #5bc0de;
            }

            .cd-parent {
              padding: 0;
              height: auto;
            }

            .cd-parent .title {
              padding: 10px 15px;
            }

            .cd-parent .holder {
              /*display: none;*/
            }

            .no-sort {
              display: none;
            }

            #saveorderpanel {
              display: none;
            }

            .spanSubmission {
              margin-left: 5px;
              background-color: #3a87ad;
              border-radius: 9px;
              /* font-weight: 600; */
              display: inline-block;
              padding: 2px 4px;
              font-size: 10.998px;
              font-weight: bold;
              line-height: 14px;
              color: #ffffff;
              vertical-align: baseline;
              white-space: nowrap;
              text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
              padding-left: 9px;
              padding-right: 9px;
            }

            .limit {
              height: 26px;
              overflow: hidden;
              float: left;
              line-height: 25px;
              text-overflow: ellipsis;
            }
          </style>
          <div class="list-group content-parent">
            <div class="list-group-item active no-sort">
                <span style="padding-left:14px">
                    Kéo thả để thay đổi vị trí các nội dung
                </span>
            </div>

            <% @lessons.each do |lesson| %>
                <div class="list-group-item">
                  <div class="col-sm-10 col-left">
                    <span class="col-sm-6 col-title limit" style="padding-left:14px;float:left">
                        <%= link_to lesson.name, lesson_detail_path(id: lesson.id) %>
                    </span>
                    <span class="col-sm-3 col-status">
                      <% if lesson.approved %>
                        <span class="label label-success">Đã duyệt</span>
                      <% else %>
                        <span class="label label-danger">Chưa duyệt</span>
                      <% end %>
                    </span>
                    <span class="col-sm-3 col-author"><%= lesson.user ? lesson.user.username : '' %></span>
                  </div>
                  <div class="col-sm-2 col-right">
                    <i class="glyphicon-handle glyphicon glyphicon-remove-circle margin-right margin-left" onclick="DeleteContent('content',10631)"></i>
                    <i class="glyphicon-handle glyphicon glyphicon-pencil margin-left margin-right kbtn-hidden" onclick="EditContent(10631, 'scorm')"></i>
                  </div>
                </div>
            <% end %>

          </div>
          <div id="saveorderpanel" class="button-action-group">
            <button class="btn btn-save btn-fixed-width" onclick="SaveOrder()">Lưu</button>
            <button class="btn btn-cancel btn-fixed-width" onclick="StopOrder()">Hủy</button>
          </div>
          <div id="content_pub_confirm" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
            <div class="modal-dialog modal-sm" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span></button>
                  <h4 class="modal-title" id="mySmallModalLabel">Bạn muốn duyệt nội dung này?</h4>
                </div>
                <div class="modal-body">
                  <div class="row" style="text-align:center">
                    <button class="btn btn-save btn-fixed-width" data-val="approve_content" data-vel="" onclick="UpdateContentStatus(this)">Duyệt</button>
                    <button class="btn btn-cancel btn-fixed-width" data-val="return_content" data-vel="" onclick="UpdateContentStatus(this)">Trả
                      lại
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div id="content_pub_cancel" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
            <div class="modal-dialog modal-sm" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span></button>
                  <h4 class="modal-title" id="mySmallModalLabel">Bạn muốn trả lại nội dung này?</h4>
                </div>
                <div class="modal-body">
                  <div class="row" style="text-align:center">
                    <button class="btn btn-cancel btn-fixed-width" data-val="return_content" data-vel="" onclick="UpdateContentStatus(this)">Trả
                      lại
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id="licenseModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">

            <div style="padding:20px;">
              <div id="license-course" class="modal-body">

              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-cancel btn-fixed-width" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span></button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id="viewRating" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document" style="">
          <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span></button>
          <div class="modal-content">

          </div>
        </div>
      </div>
    </div>
    <div id="CourseList" class="modal fade" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">

        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal danh sach bai hoc -->
    <div id="CDCreator" class="modal fade" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span></button>
            <h4 style="text-align:center" class="modal-title">Thêm chuyên đề</h4>
          </div>
          <div class="modal-body">
            <form class="form-horizontal">
              <div class="form-group">
                <label for="txtchuyende" class="col-sm-2 control-label">Chuyên đề</label>
                <div class="col-sm-10">
                  <input class="form-control" id="txtchuyende" placeholder="Tên chuyên đề..." type="text">
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer" style="text-align:center;">
            <button id="btnaddcd" type="button" class="btn btn-save btn-fixed-width" onclick="CreateCD()">Lưu</button>
            <button id="btnupdatecd" type="button" class="btn btn-save btn-fixed-width" data-id="" style="display:none" onclick="UpdateCD()">Cập
              nhật
            </button>
            <button type="button" class="btn btn-cancel btn-fixed-width" data-dismiss="modal">Hủy</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal tao chuyen de -->

  </div>
</div>

app/views/course/index.html.erb
<button class="btn btn-primary" data-toggle="modal" data-target="#add-course-modal">
  <i class="fa fa-plus">&nbsp;Them khoa hoc</i></button>
<!-- Modal -->
<div id="add-course-modal" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="padding-left: 13px;">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <%= render 'new' %>
    </div>
  </div>
</div>
<div id="course-list">
  <%= render 'list' %>
</div>

<style>
    .register_error_log {
        display: inline;
        color: #fff;
        font-size: 12px;
        margin-top: 2px;
        /*float: right;*/
        background: #d9534f;
    }

    .register_error_logVideo {
        display: inline;
        color: #fff;
        font-size: 12px;
        margin-top: 2px;
        /*float: right;*/
        background: #d9534f;
    }

    .btn-file input[type=file] {
        position: absolute;
        top: 0;
        right: 0;
        min-width: 100%;
        min-height: 100%;
        font-size: 100px;
        text-align: right;
        filter: alpha(opacity=0);
        opacity: 0;
        outline: none;
        background: white;
        cursor: inherit;
        display: block;
    }

    #btn-remove-image {
        width: 17px;
        height: 17px;
        z-index: 2;
        position: absolute;
        color: #808080;
        border-radius: 50%;
        border: solid 1px;
        background: none;
        display: none;
        right: 5px;
        top: 5px;
        font-size: 10px;
    }

    .Video-remove-icon {
        width: 17px;
        height: 17px;
        z-index: 2;
        position: absolute;
        color: #808080;
        border-radius: 50%;
        border: solid 1px;
        background: none;
        display: none;
        right: 5px;
        top: 5px;
        font-size: 10px;
    }

    .Video-remove-icon:hover {
        color: #f48c11 !important;
    }

    #btn-remove-image:hover {
        color: #f48c11 !important;
    }

    #khuploadphoto:hover #PictureIcon {
        color: #f48c11 !important;
    }

    #khuploadvideo:hover .VideoIcon {
        color: #f48c11 !important;
    }

    .dropdown-combobox-group {
        border: 1px solid #ccc;
        width: 300px;
        padding-left: 10px;
        float: left;
        position: relative;
        margin-top: -3px;
    }

    .dropdown-combobox-group > *:first-child {
        position: absolute;
        top: 50%;
        transform: translate(0,-50%);
    }

    .dropdown-combobox-group > button {
        float: right;
        border: none;
        background: #ccc;
        height: 100%;
        padding: 0px 7px;
        font-size: 20px;
        outline: none;
    }

    .dropdown-combobox-group > button + * {
        position: absolute;
        border: 1px solid #ccc;
        top: 32px;
        left: 0px;
        width: 100%;
        background: white;
        display: none;
        z-index: 99;
    }

    .dropdown-combobox-group > button + * > * {
        padding: 3px 10px;
    }

    .dropdown-combobox-group > button + * > *:hover {
        color: white;
        background: #f4a211;
        cursor: pointer;
    }

    .dropdown-combobox-group > button + * > *:not(:last-child) {
        border-bottom: 1px solid #ccc;
    }

    .tablecourse {
        width: 100%;
        table-layout: fixed;
    }

    .tablecourse > thead > tr > th {
        padding: 5px;
        text-align: left;
        font-style: normal;
    }

    .tablecourse > thead > tr > th:first-child {
        width: 30%;
    }

    .tablecourse > thead > tr > th.text-center {
        text-align: center;
    }

    .tablecourse > tbody > tr > td {
        padding: 5px;
        text-align: left;
    }

    .tablecourse > tbody > tr > td.text-center {
        text-align: center;
    }

    #vunggiaovien > tbody > tr > td > span:hover {
        cursor: pointer;
    }
</style>