config/routes.rb
Rails.application.routes.draw do

  # Route for commontator
  mount Commontator::Engine => '/commontator'

  devise_for :admins
  root to: 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get '/quan-ly-nguoi-dung', to: 'user#index', as: 'user'
  get '/quan-ly-nhom-nguoi-dung', to: 'group#index', as: 'group'
  post '/add-user', to: 'user#add_list'
  get '/nguoi-dung/:id/sua', to: 'user#edit', as: 'user_edit'
  patch '/nguoi-dung/:id/sua', to: 'user#update', as: 'user_update'

  get '/groups/new', to: 'group#new'
  post '/groups/new', to: 'group#create'

  get '/quan-ly-khoa-hoc', to: 'course#index', as: 'course'
  post '/courses/new', to: 'course#create', as: 'course_new'
  get '/khoa-hoc/:id/chi-tiet', to: 'course#detail', as: 'course_detail'

  get '/quan-ly-chu-de', to: 'topic#index', as: 'topic'
  post '/topics/new', to: 'topic#create', as: 'topic_new'

  get '/them-noi-dung/:course_id/:type_id', to: 'lesson#new', as: 'lesson_new'
  post '/them-noi-dung/:course_id/:type_id', to: 'lesson#create', as: 'lesson_create'
  get '/noi-dung/:id/sua', to: 'lesson#edit', as: 'lesson_edit'
  patch '/noi-dung/:id/sua', to: 'lesson#update', as: 'lesson_update'

  get '/noi-dung-bai-hoc/:id', to: 'lesson#show', as: 'lesson_detail'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  acts_as_commontator

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login
  belongs_to :group, optional: true

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end


  validates :username,
            :presence => true,
            :uniqueness => {
                :case_sensitive => false
            }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, :only => [:add_list]
  require 'rubygems'
  require 'roo'

  def index
    @users = User.all
  end

  def add_list
    uploader = UserUploader.new
    uploader.store!(params[:file])

    list = Roo::Spreadsheet.open "#{Rails.public_path}/#{uploader.store_path}"
    sheet = list.sheet(0)
    sheet.each() do |row|
      p = User.new
      p.username = row[0]
      p.email = row[1]
      p.password = row[2]
      if p.save
        logger.debug "Luu nguoi dung thanh cong"
      else
        logger.debug "Loi: #{p.errors.messages}"
      end
    end
    uploader.remove!
    respond_to do |format|
      format.js
    end
    @users = User.all
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update(user_params)
      @edit_result = "success"
    else
      Rails.logger.info(@user.errors.messages.inspect)
      @edit_result = @user.errors
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :username, :first_name, :last_name, :sex, :active, :date_of_birth, :phone, :address, :workplace,
                                 :academic_degree, :public_info, :biography, :group_id)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/_edit.html.erb
<div role="tabpanel" class="tab-pane active" id="userInfo">
  <%= form_for @user, url: user_update_path(id: @user.id), html: {id: "editUserInfo", style: "max-width: 800px; margin: 0 auto;"}, remote: true do |f| %>
      <!--<form id="editUserInfo" style="max-width: 800px; margin: 0 auto;">-->
      <div class="row">
        <div class="col-md-12">
          <h5 class="text-italic">(*) Thông tin bắt buộc</h5>
        </div>
        <div class="col-md-6 col-sm-8">
          <div class="lms-input-group">
            <div class="input-group-title right">Tên (*)</div>
            <div class="input-group-content">
              <!--<input name="EditFirstName" value="<%= @user.first_name %>" class="form-control" maxlength="15" type="text">-->
              <%= f.text_field :first_name, class: "form-control", value: @user.first_name, maxlength: "15" %>
            </div>
            <span class="error-message firstname-error pull-right"></span>
          </div>

          <div class="lms-input-group">
            <div class="input-group-title right">Họ (*)</div>
            <div class="input-group-content">
              <!--<input name="EditLastName" value="<%= @user.last_name %>" class="form-control" maxlength="50" type="text">-->
              <%= f.text_field :last_name, class: "form-control", value: @user.last_name, maxlength: "50" %>
            </div>
            <span class="error-message lastname-error pull-right"></span>
          </div>

          <div class="lms-input-group">
            <div class="input-group-title right">Tên đăng nhập (*)</div>
            <div class="input-group-content">
              <!--<input name="EditUserName" value="<%= @user.username %>" maxlength="32" class="form-control" type="text">-->
              <%= f.text_field :username, class: "form-control", value: @user.username, maxlength: "32" %>
            </div>
            <span class="error-message username-error pull-right"></span>
          </div>

          <div class="lms-input-group">
            <div class="input-group-title right">Mật khẩu</div>
            <div class="input-group-content">
              <!--<input name="EditPassword" value="" maxlength="32" class="form-control" type="password">-->
              <%= f.password_field :password, class: "form-control", maxlength: "32" %>
            </div>
            <span class="error-message password-error pull-right"></span>
          </div>

          <div class="lms-input-group">
            <div class="input-group-title right">Email (*)</div>
            <div class="input-group-content">
              <!--<input name="EditEmail" value="<%= @user.email %>" class="form-control" maxlength="100" type="text">-->
              <%= f.email_field :email, class: "form-control", maxlength: "100" %>
            </div>
            <span class="error-message email-error pull-right"></span>
          </div>
        </div>
        <div class="col-md-6 col-sm-4">
          <div class="select-file">
            <div class="select-file-title text-center">Ảnh đại diện</div>
            <div class="select-file-thumbs no-selected" style="margin: 0 auto;" title="" data-toggle="tooltip" data-html="true" data-placement="bottom" data-original-title="Định dạng: JPG, PNG, BMP, GIF<br/\>Dung lượng tối đa: 3MB">
              <span class="icon fa fa-camera" style="display: inline-block"></span>
              <img class="img-thumbs" style="display: none">
              <input name="EditAvatar" id="iptEditAvatar" accept="image/x-png, image/gif, image/jpeg, image/bmp" value="" class="hide" data-size="3" data-invalid="Vui lòng chọn tập tin hình ảnh dưới 3MB" type="file">
              <button type="button" class="btn-select-file"></button>
              <button type="button" class="btn-remove-file" style="display: none" title="Xoá ảnh">×</button>
            </div>
            <div class="text-center">
              <span class="error-message avatar-error"></span>
            </div>
          </div>
        </div>
      </div>
      <div class="separator"></div>
      <div class="row">
        <div class="col-md-12">
          <h5 class="text-italic">Thông tin người dùng</h5>
        </div>
        <div class="col-md-6 col-sm-6">
          <div class="lms-input-group">
            <div class="input-group-title right">Giới tính</div>
            <div class="input-group-content">
              <div class="group">
                <% if @user.sex == 1 %>
                    <%= f.radio_button :sex, '1', checked: true %>
                <% else %>
                    <%= f.radio_button :sex, '1' %>
                <% end %>
                <label for="radEditGenderMale" class="group-label input-label">Nam</label>
              </div>
              <div class="group">
                <% if @user.sex == 2 %>
                    <%= f.radio_button :sex, '2', checked: true %>
                <% else %>
                    <%= f.radio_button :sex, '2' %>
                <% end %>
                <label for="radEditGenderFemale" class="group-label input-label">Nữ</label>
              </div>
            </div>
          </div>

          <div class="lms-input-group">
            <div class="input-group-title right">Ngày sinh</div>
            <div class="input-group-content form-group has-feedback">
              <!--<input name="EditBirthday" value="" class="form-control" type="text">-->
              <%= f.text_field :date_of_birth, id: 'date-of-birth-select', class: "form-control", value: @user.date_of_birth ? @user.date_of_birth.strftime("%d/%m/%Y ") : "" %>
              <span class="fa fa-calendar form-control-feedback"></span>
            </div>
            <span class="error-message birthday-error pull-right"></span>
          </div>

          <div class="lms-input-group">
            <div class="input-group-title right">Số điện thoại</div>
            <div class="input-group-content">
              <%= f.text_field :phone, class: "form-control", value: @user.phone %>
            </div>
            <span class="error-message phoneno-error pull-right"></span>
          </div>

          <div class="lms-input-group">
            <div class="input-group-title right">Địa chỉ</div>
            <div class="input-group-content">
              <!--<input name="EditAddress" value="" class="form-control" maxlength="255" type="text">-->
              <%= f.text_field :address, class: "form-control", value: @user.address, maxlength: 255 %>
            </div>
            <span class="error-message pull-right"></span>
          </div>

          <div class="lms-input-group">
            <div class="input-group-title right">Công ty</div>
            <div class="input-group-content">
              <!--<input name="EditCompany" value="" class="form-control" maxlength="255" type="text">-->
              <%= f.text_field :workplace, class: "form-control", value: @user.workplace, maxlength: 255 %>
            </div>
            <span class="error-message pull-right"></span>
          </div>

          <div class="lms-input-group">
            <div class="input-group-title right">Học hàm</div>
            <div class="input-group-content">
              <!--<input name="academic_degree" value="" class="form-control" maxlength="50" type="text">-->
              <%= f.text_field :academic_degree, class: "form-control", value: @user.academic_degree, maxlength: 50 %>
            </div>
            <span class="error-message pull-right"></span>
          </div>
        </div>
        <div class="col-md-6 col-sm-6">
          <div class="lms-input-group">
            <div class="input-group-title">Kích hoạt</div>
            <!--<div class="group">-->
            <!--<input name="EditActive" id="radEditActive" value="True" checked="" type="radio">-->
            <!--<label for="radEditActive" class="group-label input-label">Có</label>-->
            <!--</div>-->
            <!--<div class="group">-->
            <!--<input name="EditActive" id="radEditInactive" value="False" type="radio">-->
            <!--<label for="radEditInactive" class="group-label input-label">Không</label>-->
            <!--</div>-->
            <% if @user.active == 1 %>
                <div class="group">
                  <%= f.radio_button :active, '1', checked: true %>
                  <label for="radEditActive" class="group-label input-label">Có</label>
                </div>
                <div class="group">
                  <%= f.radio_button :active, '0' %>
                  <label for="radEditActive" class="group-label input-label">Không</label>
                </div>
            <% else %>
                <div class="group">
                  <%= f.radio_button :active, '1' %>
                  <label for="radEditActive" class="group-label input-label">Có</label>
                </div>
                <div class="group">
                  <%= f.radio_button :active, '0', checked: true %>
                  <label for="radEditActive" class="group-label input-label">Không</label>
                </div>
            <% end %>
          </div>
          <div class="lms-input-group">
            <span class="input-group-title">Công khai thông tin</span>

            <!--<div class="group">-->
              <!--<input name="EditPublic" id="radEditPublic" value="True" checked="" type="radio">-->
              <!--<label for="radEditPublic" class="group-label input-label">Có</label>-->
            <!--</div>-->
            <!--<div class="group">-->
              <!--<input name="EditPublic" id="radEditUnpublic" value="False" type="radio">-->
              <!--<label for="radEditUnpublic" class="group-label input-label">Không</label>-->
            <!--</div>-->
            <% if @user.public_info == 1 %>
                <div class="group">
                  <%= f.radio_button :public_info, '1', checked: true %>
                  <label for="radEditActive" class="group-label input-label">Có</label>
                </div>
                <div class="group">
                  <%= f.radio_button :public_info, '0' %>
                  <label for="radEditActive" class="group-label input-label">Không</label>
                </div>
            <% else %>
                <div class="group">
                  <%= f.radio_button :public_info, '1' %>
                  <label for="radEditActive" class="group-label input-label">Có</label>
                </div>
                <div class="group">
                  <%= f.radio_button :public_info, '0', checked: true %>
                  <label for="radEditActive" class="group-label input-label">Không</label>
                </div>
            <% end %>
          </div>

          <div class="lms-input-group">
            <div class="input-group-title">Tiểu sử</div>
            <!--<textarea class="form-control" name="EditBio" style="height: 196px;" maxlength="3000"></textarea>-->
            <%= f.text_area :biography, class: "form-control", value: @user.biography, maxlength: 3000, style: "height: 156px;" %>
            <span class="error-message pull-right"></span>
          </div>

          <div class="lms-input-group">
            <div class="input-group-title">Kiểu người dùng</div>
            <div class="input-group-content">
              <!--<select name="EditUserType" class="form-control">-->
                <!--<option value="3207">Quản trị viên cấp cao</option>-->
                <!--<option value="3208">Quản trị viên</option>-->
                <!--<option value="3209">Người dạy</option>-->
                <!--<option value="3210" selected="">Người học</option>-->
                <!--<option value="3708">test kieu nguoi dung</option>-->
              <!--</select>-->
              <%= f.collection_select :group_id, Group.all, :id, :name, prompt: true %>
            </div>
          </div>
        </div>
      </div>
      <div class="button-action-group">
        <!--<button class="btn btn-save btn-fixed-width xm-btn-full-width" type="button" id="btnEditUser">Lưu</button>-->
        <%= f.submit "Lưu", class: "btn btn-save btn-fixed-width xm-btn-full-width" %>
        <button class="btn btn-cancel btn-fixed-width xm-btn-full-width" type="button" onclick="redirectTo('/users/index')">Huỷ</button>
      </div>
      <!--</form>-->
  <% end %> <!-- end form -->
</div>

app/views/user/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th class="text-center btn-group-1"><input id="check-all-delete-js" type="checkbox"></th>
    <th class="text-left">Tên người dùng</th>
    <th class="text-left mobile-hide">Tên đăng nhập</th>
    <th class="text-left mobile-hide">Kiểu người dùng</th>
    <th class="date mobile-hide">Ngày tham gia</th>
    <th class="btn-group-3">Chức năng</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr data-id="4372" style="display: table-row;" class="paginationItemPage1">
        <td class="text-center btn-group-1">
          <input class="one-delete-js" type="checkbox">
        </td>
        <td class="key">
          <%= link_to user.username, user_edit_path(id: user.id) %>
        </td>
        <td class="key mobile-hide"><%= user.username %></td>
        <td class="key mobile-hide">Người học</td>
        <td class="text-center key mobile-hide"><%= user.created_at.strftime("%d/%m/%Y ") %></td>
        <td class="text-center">
          <a class="btn btn-action" href="/userreport/details/4372" title="Báo cáo">
            <span class="fa fa-area-chart"></span>
          </a>
          <%= link_to "<span class='fa fa-pencil'></span>".html_safe, user_edit_path(id: user.id) %>
          <button class="btn btn-action" title="Xoá">
            <span class="fa fa-trash"></span>
          </button>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/user/add_list.js.erb
$('#user-list').html("<%= j render partial: 'list' %>")

app/views/user/index.html.erb
<h2>Quan ly nguoi dung</h2>

<div class="user-control-nav">
  <form enctype="multipart/form-data">
    <input name="file" type="file"/>
    <input type="button" value="Upload" id="btn-excel-submit"/>
  </form>
</div>

<div id="user-list">
  <%= render 'list' %>
</div>
<script>
    $(':file').on('change', function () {
        var file = this.files[0];
        if (file.size > 5 * 1024 * 1024) {
            alert('max upload size is 5M')
        }
    });

    $('#btn-excel-submit').on('click', function () {
        $.ajax({
            url: '/add-user',
            type: 'POST',

            // Form data
            data: new FormData($('form')[0]),

            // Tell jQuery not to process data or worry about content-type
            // You *must* include these options!
            cache: false,
            contentType: false,
            processData: false,

            // Custom XMLHttpRequest
            xhr: function () {
                var myXhr = $.ajaxSettings.xhr();
                if (myXhr.upload) {
                    // For handling the progress of the upload
                    myXhr.upload.addEventListener('progress', function (e) {
                        if (e.lengthComputable) {
                            $('progress').attr({
                                value: e.loaded,
                                max: e.total,
                            });
                        }
                    }, false);
                }
                return myXhr;
            },
            success: function (data) {
            },
            error: function (jqXHR, textStatus, errorThrown) {
            }
        });
    });
</script>

app/views/user/update.js.erb
alert("<%= @edit_result %>")