config/routes.rb
Rails.application.routes.draw do

  # Route for commontator
  mount Commontator::Engine => '/commontator'

  devise_for :admins
  root to: 'home#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get '/quan-ly-nguoi-dung', to: 'user#index', as: 'user'
  get '/quan-ly-nhom-nguoi-dung', to: 'group#index', as: 'group'
  post '/add-user', to: 'user#add_list'
  get '/nguoi-dung/:id/sua', to: 'user#edit', as: 'user_edit'
  patch '/nguoi-dung/:id/sua', to: 'user#update', as: 'user_update'

  get '/groups/new', to: 'group#new'
  post '/groups/new', to: 'group#create'

  get '/quan-ly-khoa-hoc', to: 'course#index', as: 'course'
  post '/courses/new', to: 'course#create', as: 'course_new'
  get '/khoa-hoc/:id/chi-tiet', to: 'course#detail', as: 'course_detail'

  get '/quan-ly-chu-de', to: 'topic#index', as: 'topic'
  post '/topics/new', to: 'topic#create', as: 'topic_new'

  get '/them-noi-dung/:course_id/:type_id', to: 'lesson#new', as: 'lesson_new'
  post '/them-noi-dung/:course_id/:type_id', to: 'lesson#create', as: 'lesson_create'
  get '/noi-dung/:id/sua', to: 'lesson#edit', as: 'lesson_edit'
  patch '/noi-dung/:id/sua', to: 'lesson#update', as: 'lesson_update'

  get '/noi-dung-bai-hoc/:id', to: 'lesson#show', as: 'lesson_detail'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/controllers/topic_controller.rb
class TopicController < ApplicationController
  before_action :authenticate_user!

  skip_before_action :verify_authenticity_token, :only => [:create]
  def index
    @topics = Topic.all
	@topic = Topic.new
  end

  def new
    respond_to do |format|
      format.html{redirect_to '/quan-ly-chu-de'}
      format.js
    end
  end

  def create
	@topic = Topic.new(topic_params)
    if @topic.save
      @topics = Topic.all
      respond_to do |format|
        format.js
      end
    end
  end
  
  private
  def topic_params
	params.require(:topic).permit(:name, :description)
  end
end

app/views/topic/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th>Chủ đề</th>
    <th>Chức năng</th>
  </tr>
  </thead>
  <tbody>
  <% if @topics.length > 0 %>
      <% @topics.each do |topic| %>
          <tr>
            <td><%= topic.name %></td>
            <td>
              <span class="fa fa-pencil"></span>
              <span class=" fa fa-trash-o" title="Xoá"></span>
            </td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/topic/_new.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content" style="padding-top:20px">
    <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
    </button>
    <h4 style="font-size:14px;text-align:center" id="titleUtypes">THÊM CHỦ ĐỀ</h4>
    <div class="separator"></div>
    <div class="row">
	  <%= form_for @topic, url: topic_new_path, remote: true, id: "topic-new-form" do |f| %> 
      <div class="col-md-12">
        <div class="lms-input-group">
          <div class="input-group-title right">Chủ đề</div>
          <div class="input-group-content">
            <%= f.text_field :name, class: "form-control", maxlength: 255, style: "border: 1px solid rgb(204, 204, 204);" %>
		  </div>
          <span id="errorNameCourse" class="error-message firstname-error pull-right" style="display: none;"></span>
        </div>
		<div class="lms-input-group">
          <div class="input-group-title right">Mô tả</div>
		  <div class="input-group-content">
            <%= f.text_area :description, class: "form-control", maxlength: 4000, style: "border: 1px solid rgb(204, 204, 204);", rows: 10 %>
		  </div>
		</div>
      </div>
	  <div class="button-action-group">
          <button id="btn-save-group" class="btn btn-save btn-fixed-width xm-btn-full-width" value="Lưu">Lưu</button>
          <button class="btn btn-cancel btn-fixed-width xm-btn-full-width" data-dismiss="modal" value="Hủy">Huỷ</button>
      </div>
	  <% end %>
    </div>
  </div>
</div>

app/views/topic/create.js.erb
$("#topic-list").html("<%= j render partial: 'list' %>");
$('#add-topic-modal').modal('hide');

app/views/topic/index.html.erb
<button class="btn btn-primary" data-toggle="modal" data-target="#add-topic-modal">
  <i class="fa fa-plus">&nbsp;Them chu de</i></button>
<!-- Modal -->
<div class="modal fade" id="add-topic-modal" role="dialog">
  <%= render 'new' %>
</div>
<div id="topic-list">
  <%= render 'list' %>
</div>